server:
  port: 8081


spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://localhost:8080/eureka
